### ISSUE TITLE
Strange Build Errors

### ISSUE THREAD

**Issue by BOBONA** [adamski/PitchDetector#5]
Hi. I am interested in using your pitch detection code for a sampler plugin I'm working on. I believe I installed it correctly along with the audio_fft dependency. When I try to build the plugin, I get hundreds of errors in juce_Array, juce_ArrayBase, juce_HeapBlock like "you cannot create a pointer to a reference" and "member function already declared." Do you know what could cause this? I wish I had more details to share but I'm really confused about this...

**Comment by adamski** [comment]
I assume this was solved?

**Comment by BOBONA** [comment]
Yeah, sorry about that. It was me misunderstanding strange build errors
that were actually being caused by something else. I got it working though.
Thanks for making this module!
